name: CI - Zukii Python Service

on:
  push:
    branches: [ main, dev ]
    tags: ['bloc2-*']
  pull_request:
    branches: [ main, dev ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black flake8

      - name: Run unit tests (pytest)
        working-directory: .
        run: pytest -q

      - name: Lint (ruff)
        run: ruff check app tests

      - name: Lint (flake8)
        run: flake8 app tests

      - name: Format check (black)
        run: black --check app tests

      - name: Upload anonymization logs (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-logs
          path: |
            logs
          if-no-files-found: ignore
          retention-days: 14

  docker:
    name: Build et Publication Docker
    runs-on: ubuntu-latest
    needs: [tests]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build et Publication Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/guillaumesrn/zukii-python:latest
            ghcr.io/guillaumesrn/zukii-python:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

