name: Deploy Python Service to OVH VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy Python Service to OVH VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.OVH_HOST }}
          username: ${{ secrets.OVH_USER }}
          key: ${{ secrets.OVH_SSH_KEY }}
          script: |
            cd ~/zukii-app
            echo "🐍 DÉPLOIEMENT SERVICE PYTHON - C2.2.4"
            
            # Pull et déploiement
            docker compose pull python-service
            docker compose up -d python-service
            
            # Health check Python avec retry (tolérant au mode offline)
            echo "⏳ Vérification du service Python..."
            for i in {1..15}; do
              if docker compose exec -T python-service sh -c "curl -sf http://localhost:8000/health" >/dev/null 2>&1; then
                echo "✅ Service Python opérationnel (tentative $i/15)"
                break
              fi
              if [ $i -eq 15 ]; then
                echo "⚠️ Service Python non accessible (mode offline possible) - Déploiement continué"
                break
              fi
              echo "⏳ Tentative $i/15 - Attente 2s..."
              sleep 2
            done
            
            echo "🎉 Service Python déployé avec succès sur OVH !"
            echo "🐍 Service d'analyse IA opérationnel"
